server:
  port: 9006

spring:
  application:
    name: langchain4j-06chat-image

langchain4j:
  open-ai:
    chat-model:
      api-key: ${ALI_AI_KEY}
      model-name: qwen-vl-max-2025-04-08
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1