
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5437/ray_wing
    username: postgres
    password: wrp@PGatSMGI0601
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 120000
      maximum-pool-size: 32
      minimum-idle: 8
      auto-commit: true

  data:
    redis:
      host: localhost
      password: wrp@REDISatSMGI0601

  ## SecurityProperties，修改默认配置
  security:
    user:
      name: admin
      password: 123

    oauth2:
      client:
        registration:
          # 授权码方式oauth2
          github:
            client-id: abc
            client-secret: ccc

logging:
  level:
    com:
      wrp:
        user: debug
#    org:
#      springframework: debug
