
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ray_wing
    username: postgres
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 120000
      maximum-pool-size: 32
      minimum-idle: 8
      auto-commit: true

  data:
    redis:
      host: 172.27.100.217
      password: redis123456

  ## SecurityProperties，修改默认配置
  security:
    user:
      name: admin
      password: 123


logging:
  level:
    com:
      wrp:
        user: debug
    org:
      springframework: debug
