server:
  port: 9014
  servlet:
    # 设置编码格式，防止流式响应返回乱码
    encoding:
      charset: utf-8
      enabled: true
      force: true


spring:
  application:
    name: langchain4j-14chat-mcp

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${ALI_AI_KEY}
        model-name: qwen-plus-2025-04-28
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

      chat-model:
        ## 从环境变量读取
        api-key: ${ALI_AI_KEY}
        model-name: qwen-plus-2025-04-28
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1