services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123456
    command: redis-server  /usr/local/etc/redis/redis.conf